resolver: lts-6.5
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
extra-include-dirs:
- /usr/local/opt/readline/include
extra-lib-dirs:
- /usr/local/opt/readline/lib

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
