resolver: lts-6.5
packages:
- '.'
extra-deps: []
flags:
  questioner:
    examples: true
extra-package-dbs: []
extra-include-dirs:
- /usr/local/opt/readline/include
extra-lib-dirs:
- /usr/local/opt/readline/lib
